from typing import Protocol

from app.domain.tags.models import StockTag, TagCategory, TagDefinition


class TagRepository(Protocol):
    def list_categories(self) -> list[TagCategory]: ...
    def list_tags(self) -> list[TagDefinition]: ...
    def create_category(self, category: TagCategory) -> TagCategory: ...
    def update_category(self, category_id: int, category: TagCategory) -> TagCategory: ...
    def delete_category(self, category_id: int) -> None: ...
    def create_tag(self, tag: TagDefinition) -> TagDefinition: ...
    def update_tag(self, tag_id: int, tag: TagDefinition) -> TagDefinition: ...
    def delete_tag(self, tag_id: int) -> None: ...
    def list_stock_tags(self, ts_code: str) -> list[StockTag]: ...
    def replace_stock_tags(self, ts_code: str, tag_ids: list[int]) -> list[StockTag]: ...
