from typing import Protocol

from app.domain.stock_tracking.models import StockDetail


class StockTrackingRepository(Protocol):
    def list_tracked(self) -> list[StockDetail]: ...

    def find_by_code(self, ts_code: str) -> StockDetail | None: ...

    def save(self, detail: StockDetail) -> StockDetail: ...

    def set_tracked(self, ts_code: str, is_tracked: bool) -> StockDetail | None: ...

    def list_tracked_codes(self) -> list[str]: ...

    def save_sync_error(self, ts_code: str, error: str) -> None: ...
