import { ArrowRightOutlined, CheckCircleOutlined, LineChartOutlined } from '@ant-design/icons';
import { Alert, Card, Col, Flex, Row, Space, Tag, Typography } from 'antd';
import { useEffect, useState } from 'react';
import { fetchHomeSummary } from '../api/home';
import { fallbackHomeSummary } from '../data/fallback';

export function OverviewPage() {
  const [summary, setSummary] = useState(fallbackHomeSummary); const [loading, setLoading] = useState(true); const [offline, setOffline] = useState(false);
  useEffect(() => { fetchHomeSummary().then(setSummary).catch(() => setOffline(true)).finally(() => setLoading(false)); }, []);
  return <div className="overview page-wrap"><Flex justify="space-between" align="end" gap={32} wrap><div><Typography.Text className="product-name">{summary.productName}</Typography.Text><Typography.Text className="overline">GOOD MORNING, INVESTOR</Typography.Text><Typography.Title className="welcome-title">读懂市场，<Typography.Text italic>先人一步。</Typography.Text></Typography.Title><Typography.Paragraph className="lead">让每一次复盘都有依据，让每一个策略都可追踪。</Typography.Paragraph></div><Card size="small" className="market-chip"><Space><CheckCircleOutlined style={{ color: '#74b29d' }} /><Typography.Text type="secondary">MARKET WATCH</Typography.Text></Space><Typography.Text type="warning">{summary.statusText}</Typography.Text></Card></Flex>{offline && <Alert className="notice" type="warning" showIcon title="当前显示基础内容" description="数据服务暂时不可用" />}{loading && <Alert className="loading-bar" type="info" showIcon title="正在同步平台状态…" />}<Card className="signal-panel"><Flex justify="space-between" align="end"><div><Typography.Text type="warning">01</Typography.Text><Typography.Title level={2}>{summary.tagline}</Typography.Title></div><Typography.Text type="secondary">从市场脉络到个股变化<br />建立一套属于你的投资观察系统。</Typography.Text></Flex></Card><section className="modules"><Flex justify="space-between" align="end"><div><Typography.Text className="overline">CORE MODULES</Typography.Text><Typography.Title level={2}>你的投资工作台</Typography.Title></div><Typography.Text type="warning">EXPLORE <ArrowRightOutlined /></Typography.Text></Flex><Row gutter={[14, 14]} className="module-grid">{summary.features.map((feature, index) => <Col xs={24} md={8} key={feature.key}><Card className={`module-card ${feature.status === 'available' ? 'available' : 'coming'}`} hoverable><Flex justify="space-between"><Typography.Text type="warning">0{index + 1}</Typography.Text><Tag color={feature.status === 'available' ? 'green' : 'default'}>{feature.status === 'available' ? 'AVAILABLE' : 'COMING SOON'}</Tag></Flex><LineChartOutlined className="card-glyph" /><Typography.Title level={3}>{feature.title}</Typography.Title><Typography.Paragraph type="secondary">{feature.description}</Typography.Paragraph>{feature.status === 'available' ? <a href="/daily-review">进入模块 <ArrowRightOutlined /></a> : <Typography.Text type="secondary">即将上线</Typography.Text>}</Card></Col>)}</Row></section></div>;
}
