import { DeleteOutlined, PlusOutlined, SettingOutlined } from '@ant-design/icons';
import { Alert, Button, Checkbox, Input, Modal, Select, Space, Table, Tag, Typography, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { addTrackedStock, fetchStockDetail, fetchStockTableConfig, fetchTrackedStocks, removeTrackedStock, saveStockTableConfig, searchStocks, StockDetail, StockSearchResult, TableColumn } from '../api/stocks';
import { formatStockError, getSearchResultAction } from './stockSelector';

const labels: Record<string, string> = { stockName: '股票名称', tsCode: '股票代码', currentPrice: '当前股价', change7dPercent: '7日涨幅', peTtm: 'PE', pePercentile: 'PE历史百分位', pb: 'PB', pbPercentile: 'PB历史百分位', latestTradeDate: '最新交易日', dataSource: '数据来源' };
const fixedColumnKeys = new Set(['stockName', 'tsCode']);
const defaults: TableColumn[] = Object.keys(labels).map((key, order) => ({ key, visible: true, frozen: order < 2, searchable: !['latestTradeDate', 'dataSource'].includes(key), searchType: ['currentPrice', 'change7dPercent', 'peTtm', 'pePercentile', 'pb', 'pbPercentile'].includes(key) ? 'number' : 'text', order }));
const numberKeys = new Set(['currentPrice', 'change7dPercent', 'peTtm', 'pePercentile', 'pb', 'pbPercentile']);
const valueOf = (stock: StockDetail, key: string) => (stock as unknown as Record<string, unknown>)[key];
export const frozenOffset = (columns: TableColumn[], index: number) => columns.slice(0, index).filter((item) => item.visible && item.frozen).reduce((offset, item) => offset + (item.key === 'stockName' ? 100 : 180), 0);

function StockTable({ stocks, columns, onRemove }: { stocks: StockDetail[]; columns: TableColumn[]; onRemove: (code: string) => void }) {
  const [filters, setFilters] = useState<Record<string, string>>({});
  const visible = useMemo(() => columns.filter((item) => item.visible).sort((a, b) => a.order - b.order), [columns]);
  const displayColumns = useMemo(() => visible.filter((item) => labels[item.key] && (item.key !== 'tsCode' || !visible.some((column) => column.key === 'stockName'))), [visible]);
  const filtered = stocks.filter((stock) => visible.every((column) => { const filter = filters[column.key]?.trim(); if (!filter || !column.searchable) return true; const value = valueOf(stock, column.key); if (column.searchType === 'number') { const [min, max] = filter.split('-').map(Number); const n = Number(value); return !Number.isNaN(n) && (Number.isNaN(min) || n >= min) && (Number.isNaN(max) || n <= max); } return String(value ?? '').toLowerCase().includes(filter.toLowerCase()); }));
  const tableColumns: ColumnsType<StockDetail> = displayColumns.map((column) => ({ key: column.key, dataIndex: column.key, title: labels[column.key], fixed: column.frozen ? 'left' : undefined, width: column.key === 'stockName' ? 100 : 150, align: 'center', render: (value: unknown, stock) => column.key === 'stockName' ? <Link className="stock-name-link" to={'/stock-tracking/' + stock.tsCode}><span className="stock-name-primary">{String(value)}</span><span className="stock-name-secondary">{stock.tsCode}</span></Link> : value == null ? '—' : numberKeys.has(column.key) ? Number(value).toFixed(2) : String(value) }));
  tableColumns.push({ key: 'operation', title: '操作', fixed: 'right', width: 110, align: 'center', render: (_, stock) => <Button danger type="text" icon={<DeleteOutlined />} onClick={() => onRemove(stock.tsCode)}>移除</Button> });
  return <Space direction="vertical" size={16} style={{ width: '100%' }}><Space wrap>{visible.filter((c) => c.searchable).map((c) => <Input key={c.key} placeholder={'搜索' + labels[c.key]} value={filters[c.key] ?? ''} onChange={(e) => setFilters({ ...filters, [c.key]: e.target.value })} style={{ width: 160 }} />)}</Space><Table<StockDetail> rowKey="tsCode" size="middle" bordered sticky scroll={{ x: 'max-content' }} columns={tableColumns} dataSource={filtered} pagination={{ pageSize: 20, showSizeChanger: false }} /></Space>;
}

function ConfigModal({ columns, onSave, onClose }: { columns: TableColumn[]; onSave: (columns: TableColumn[]) => Promise<void>; onClose: () => void }) {
  const [draft, setDraft] = useState(columns); const [saving, setSaving] = useState(false); const sorted = [...draft].sort((a, b) => a.order - b.order); const configurable = sorted.filter((item) => !fixedColumnKeys.has(item.key)); const update = (key: string, patch: Partial<TableColumn>) => setDraft((items) => items.map((item) => item.key === key ? { ...item, ...patch } : item));
  const move = (key: string, delta: number) => { const next = [...sorted]; const index = next.findIndex((item) => item.key === key); const target = index + delta; if (target < 0 || target >= next.length || fixedColumnKeys.has(next[target].key)) return; [next[index], next[target]] = [next[target], next[index]]; setDraft(next.map((item, order) => ({ ...item, order }))); };
  const save = async () => { setSaving(true); try { await onSave(draft); } finally { setSaving(false); } };
  return <Modal open title="配置表头" onCancel={onClose} onOk={() => void save()} okText={saving ? '保存中…' : '保存配置'} confirmLoading={saving} width={760}><Alert type="info" showIcon message="股票名称、股票代码固定展示、冻结、可搜索，不参与配置。" description="其他字段可设置展示、冻结、搜索和搜索类型；操作列始终固定在最右侧。" style={{ marginBottom: 16 }} /><Space direction="vertical" style={{ width: '100%' }}>{configurable.map((item) => <Space key={item.key} className="config-row" wrap><Typography.Text strong style={{ width: 120 }}>{labels[item.key] ?? '操作'}</Typography.Text><Checkbox checked={item.visible} disabled={item.key === 'operation'} onChange={(e) => update(item.key, { visible: e.target.checked })}>展示</Checkbox><Checkbox checked={item.frozen} disabled={item.key === 'operation'} onChange={(e) => update(item.key, { frozen: e.target.checked })}>冻结</Checkbox><Checkbox checked={item.searchable} disabled={item.key === 'operation'} onChange={(e) => update(item.key, { searchable: e.target.checked })}>搜索</Checkbox>{item.searchable && item.key !== 'operation' && <Select value={item.searchType} onChange={(value: TableColumn['searchType']) => update(item.key, { searchType: value })} options={[{ value: 'text', label: '文本模糊' }, { value: 'number', label: '数值范围' }, { value: 'enum', label: '枚举选择' }]} style={{ width: 120 }} />}<Button size="small" onClick={() => move(item.key, -1)}>↑</Button><Button size="small" onClick={() => move(item.key, 1)}>↓</Button></Space>)}</Space></Modal>;
}

export function StockTrackingPage() {
  const [stocks, setStocks] = useState<StockDetail[]>([]); const [columns, setColumns] = useState<TableColumn[]>(defaults); const [configOpen, setConfigOpen] = useState(false); const [addOpen, setAddOpen] = useState(false); const [query, setQuery] = useState(''); const [results, setResults] = useState<StockSearchResult[]>([]); const [searching, setSearching] = useState(false); const [addingCode, setAddingCode] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const [apiMessage, contextHolder] = message.useMessage();
  const load = () => fetchTrackedStocks().then(setStocks).catch(() => apiMessage.error('列表加载失败，请检查 API 服务')).finally(() => setLoading(false)); useEffect(() => { void load(); fetchStockTableConfig().then(setColumns).catch(() => undefined); }, []);
  const search = async (e: FormEvent) => { e.preventDefault(); if (!query.trim()) return apiMessage.warning('请输入股票名称或代码'); setSearching(true); try { setResults(await searchStocks(query.trim())); } catch (error) { apiMessage.error(formatStockError(error)); } finally { setSearching(false); } };
  const add = async (item: StockSearchResult) => { if (item.isTracked || addingCode) return; setAddingCode(item.tsCode); try { await addTrackedStock(item.tsCode); setResults((items) => items.map((x) => x.tsCode === item.tsCode ? { ...x, isTracked: true } : x)); await load(); apiMessage.success('股票已添加'); } catch (error) { apiMessage.error(formatStockError(error)); } finally { setAddingCode(null); } };
  const remove = async (code: string) => { Modal.confirm({ title: '确认移除股票？', content: code, okText: '移除', cancelText: '取消', onOk: async () => { await removeTrackedStock(code); await load(); apiMessage.success('股票已移除'); } }); };
  return <>{contextHolder}<div className="module-page page-wrap"><Space direction="vertical" size={4}><Typography.Text className="overline">STOCK TRACKING</Typography.Text><Typography.Title>个股追踪</Typography.Title><Typography.Paragraph className="module-intro">可配置字段、筛选条件和冻结列的追踪表格。</Typography.Paragraph></Space><Space style={{ marginTop: 24, marginBottom: 18 }}><Button icon={<SettingOutlined />} onClick={() => setConfigOpen(true)}>表头配置</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => { setAddOpen(true); setResults([]); setQuery(''); }}>新增</Button></Space>{loading ? <Alert type="info" showIcon title="正在加载追踪列表…" /> : stocks.length ? <StockTable stocks={stocks} columns={columns} onRemove={remove} /> : <Alert type="info" showIcon title="还没有追踪股票" description="点击右上角“新增”建立观察清单。" />}{addOpen && <Modal open title="新增追踪股票" footer={null} onCancel={() => !addingCode && setAddOpen(false)}><form onSubmit={search}><Space.Compact style={{ width: '100%' }}><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索股票名称或代码" autoFocus /><Button type="primary" htmlType="submit" loading={searching}>搜索</Button></Space.Compact></form>{results.length ? <Table size="small" rowKey="tsCode" pagination={false} dataSource={results} columns={[{ title: '股票名称', dataIndex: 'stockName' }, { title: '股票代码', dataIndex: 'tsCode' }, { title: '市场', dataIndex: 'exchange' }, { title: '操作', render: (_, item) => { const action = getSearchResultAction(item.isTracked, addingCode === item.tsCode); return <Button type={item.isTracked ? 'text' : 'primary'} disabled={action.disabled} onClick={() => void add(item)}>{action.label}</Button>; } }]} style={{ marginTop: 20 }} /> : <Typography.Paragraph type="secondary" style={{ textAlign: 'center', marginTop: 24 }}>{query ? '暂无匹配股票' : '输入股票名称或代码后点击搜索'}</Typography.Paragraph>}</Modal>}{configOpen && <ConfigModal columns={columns} onClose={() => setConfigOpen(false)} onSave={async (value) => { try { const saved = await saveStockTableConfig(value); setColumns(saved); setConfigOpen(false); apiMessage.success('表头配置已保存'); } catch (error) { apiMessage.error(formatStockError(error)); } }} />}</div></>;
}

export function StockDetailPage() { const { tsCode = '' } = useParams(); const navigate = useNavigate(); const [stock, setStock] = useState<StockDetail | null>(null); useEffect(() => { fetchStockDetail(tsCode).then(setStock); }, [tsCode]); if (!stock) return <div className="module-page page-wrap"><Alert type="info" showIcon message="正在加载个股详情…" /></div>; return <div className="module-page page-wrap"><Button type="link" onClick={() => navigate('/stock-tracking')}>← 返回追踪列表</Button><Typography.Title>{stock.stockName}</Typography.Title><Typography.Paragraph type="secondary">{stock.tsCode} · 最新交易日 {stock.latestTradeDate ?? '暂无'}</Typography.Paragraph></div>; }
