import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { addTrackedStock, fetchStockDetail, fetchStockTableConfig, fetchTrackedStocks, removeTrackedStock, saveStockTableConfig, searchStocks, StockDetail, StockSearchResult, TableColumn } from '../api/stocks';
import { formatStockError, getSearchResultAction } from './stockSelector';

const labels: Record<string, string> = { stockName: '股票名称', tsCode: '股票代码', currentPrice: '当前股价', change7dPercent: '7日涨幅', peTtm: 'PE', pePercentile: 'PE历史百分位', pb: 'PB', pbPercentile: 'PB历史百分位', latestTradeDate: '最新交易日', dataSource: '数据来源' };
const defaults: TableColumn[] = Object.keys(labels).map((key, order) => ({ key, visible: true, frozen: order < 2, searchable: !['latestTradeDate', 'dataSource'].includes(key), searchType: ['currentPrice', 'change7dPercent', 'peTtm', 'pePercentile', 'pb', 'pbPercentile'].includes(key) ? 'number' : 'text', order }));
const numberKeys = new Set(['currentPrice', 'change7dPercent', 'peTtm', 'pePercentile', 'pb', 'pbPercentile']);
const valueOf = (stock: StockDetail, key: string) => (stock as unknown as Record<string, unknown>)[key];
export const frozenOffset = (columns: TableColumn[], index: number) => columns.slice(0, index).filter((item) => item.visible && item.frozen).length * 180;

function StockTable({ stocks, columns, onRemove }: { stocks: StockDetail[]; columns: TableColumn[]; onRemove: (code: string) => void }) {
  const [filters, setFilters] = useState<Record<string, string>>({}); const visible = useMemo(() => columns.filter((item) => item.visible).sort((a, b) => a.order - b.order), [columns]);
  const filtered = stocks.filter((stock) => visible.every((column) => { const filter = filters[column.key]?.trim(); if (!filter || !column.searchable) return true; const value = valueOf(stock, column.key); if (column.searchType === 'number') { const [min, max] = filter.split('-').map(Number); const n = Number(value); return !Number.isNaN(n) && (Number.isNaN(min) || n >= min) && (Number.isNaN(max) || n <= max); } return String(value ?? '').toLowerCase().includes(filter.toLowerCase()); }));
  return <div className="tracking-table-wrap"><div className="table-filters">{visible.filter((c) => c.searchable).map((c) => <input key={c.key} placeholder={`搜索${labels[c.key]}`} value={filters[c.key] ?? ''} onChange={(e) => setFilters({ ...filters, [c.key]: e.target.value })} />)}</div><div className="tracking-table-scroll"><table className="tracking-table"><thead><tr>{visible.map((c, index) => <th key={c.key} className={c.frozen ? 'frozen-column' : ''} style={c.frozen ? { left: `${frozenOffset(visible, index)}px` } : undefined}>{labels[c.key]}</th>)}<th className="operation-column">操作</th></tr></thead><tbody>{filtered.map((stock) => <tr key={stock.tsCode}>{visible.map((c, index) => <td key={c.key} className={c.frozen ? 'frozen-column' : ''} style={c.frozen ? { left: `${frozenOffset(visible, index)}px` } : undefined}>{c.key === 'stockName' ? <Link to={`/stock-tracking/${stock.tsCode}`}>{String(valueOf(stock, c.key))}</Link> : valueOf(stock, c.key) == null ? '—' : numberKeys.has(c.key) ? Number(valueOf(stock, c.key)).toFixed(2) : String(valueOf(stock, c.key))}</td>)}<td className="operation-column"><button className="text-button" onClick={() => onRemove(stock.tsCode)}>移除</button></td></tr>)}</tbody></table></div></div>;
}

function ConfigModal({ columns, onSave, onClose }: { columns: TableColumn[]; onSave: (columns: TableColumn[]) => Promise<void>; onClose: () => void }) {
  const [draft, setDraft] = useState(columns); const [saving, setSaving] = useState(false); const sorted = [...draft].sort((a, b) => a.order - b.order); const update = (key: string, patch: Partial<TableColumn>) => setDraft((items) => items.map((item) => item.key === key ? { ...item, ...patch } : item));
  const move = (index: number, delta: number) => { const next = [...sorted]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setDraft(next.map((item, order) => ({ ...item, order }))); };
  const save = async () => { setSaving(true); await onSave(draft); setSaving(false); };
  return <div className="modal-backdrop"><section className="stock-modal config-modal" role="dialog"><div className="modal-header"><h2>配置表头</h2><button className="modal-close" onClick={onClose} disabled={saving}>×</button></div><p className="config-tip">冻结列必须从第一列连续设置，操作列始终固定在最右侧。</p><div className="config-list">{sorted.map((item, index) => <div className="config-row" key={item.key}><strong>{labels[item.key] ?? '操作'}</strong><label><input type="checkbox" checked={item.visible} disabled={item.key === 'operation'} onChange={(e) => update(item.key, { visible: e.target.checked })} />展示</label><label><input type="checkbox" checked={item.frozen} disabled={item.key === 'operation'} onChange={(e) => update(item.key, { frozen: e.target.checked })} />冻结</label><label><input type="checkbox" checked={item.searchable} disabled={item.key === 'operation'} onChange={(e) => update(item.key, { searchable: e.target.checked })} />搜索</label>{item.searchable && item.key !== 'operation' && <select value={item.searchType} onChange={(e) => update(item.key, { searchType: e.target.value as TableColumn['searchType'] })}><option value="text">文本模糊</option><option value="number">数值范围</option><option value="enum">枚举选择</option></select>}<button className="move-button" onClick={() => move(index, -1)}>↑</button><button className="move-button" onClick={() => move(index, 1)}>↓</button></div>)}</div><div className="modal-footer"><button className="secondary-button" onClick={onClose}>取消</button><button className="primary-button" onClick={() => void save()} disabled={saving}>{saving ? '保存中…' : '保存配置'}</button></div></section></div>;
}

export function StockTrackingPage() {
  const [stocks, setStocks] = useState<StockDetail[]>([]); const [columns, setColumns] = useState<TableColumn[]>(defaults); const [configOpen, setConfigOpen] = useState(false); const [addOpen, setAddOpen] = useState(false); const [query, setQuery] = useState(''); const [results, setResults] = useState<StockSearchResult[]>([]); const [searching, setSearching] = useState(false); const [addingCode, setAddingCode] = useState<string | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => fetchTrackedStocks().then(setStocks).catch(() => setMessage('列表加载失败，请检查 API 服务')).finally(() => setLoading(false)); useEffect(() => { void load(); fetchStockTableConfig().then(setColumns).catch(() => undefined); }, []);
  const search = async (e: FormEvent) => { e.preventDefault(); if (!query.trim()) return setMessage('请输入股票名称或代码'); setSearching(true); try { setResults(await searchStocks(query.trim())); } catch (error) { setMessage(formatStockError(error)); } finally { setSearching(false); } };
  const add = async (item: StockSearchResult) => { if (item.isTracked || addingCode) return; setAddingCode(item.tsCode); try { await addTrackedStock(item.tsCode); setResults((items) => items.map((x) => x.tsCode === item.tsCode ? { ...x, isTracked: true } : x)); await load(); } catch (error) { setMessage(formatStockError(error)); } finally { setAddingCode(null); } };
  const remove = async (code: string) => { if (window.confirm(`确认移除 ${code}？`)) { await removeTrackedStock(code); await load(); } };
  return <div className="module-page page-wrap"><div className="module-heading"><div><p className="overline">STOCK TRACKING</p><h1>个股追踪</h1><p className="module-intro">可配置字段、筛选条件和冻结列的追踪表格。</p></div><div className="heading-actions"><button className="secondary-button" onClick={() => setConfigOpen(true)}>表头配置</button><button className="primary-button" onClick={() => { setAddOpen(true); setMessage(''); }}>新增</button></div></div>{message && <div className="notice">{message}</div>}{loading ? <div className="loading-bar">正在加载追踪列表…</div> : stocks.length ? <StockTable stocks={stocks} columns={columns} onRemove={remove} /> : <div className="empty-module"><strong>还没有追踪股票</strong><span>点击右上角“新增”建立观察清单。</span></div>}{addOpen && <div className="modal-backdrop" onClick={() => !addingCode && setAddOpen(false)}><section className="stock-modal" role="dialog" onClick={(e) => e.stopPropagation()}><div className="modal-header"><h2>新增追踪股票</h2><button className="modal-close" onClick={() => !addingCode && setAddOpen(false)}>×</button></div><form className="modal-search" onSubmit={search}><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索股票名称或代码" autoFocus /><button type="submit" disabled={searching}>{searching ? '搜索中…' : '搜索'}</button></form>{message && <div className="modal-notice">{message}</div>}{results.length ? <div className="search-result-table">{results.map((item) => { const action = getSearchResultAction(item.isTracked, addingCode === item.tsCode); return <div className="result-row" key={item.tsCode}><span>{item.stockName}</span><span>{item.tsCode}</span><span>{item.exchange}</span><button className="result-action" disabled={action.disabled} onClick={() => void add(item)}>{action.label}</button></div>; })}</div> : <div className="modal-empty">{query ? '暂无匹配股票' : '输入股票名称或代码后点击搜索'}</div>}</section></div>}{configOpen && <ConfigModal columns={columns} onClose={() => setConfigOpen(false)} onSave={async (value) => { setColumns(value); setConfigOpen(false); try { setColumns(await saveStockTableConfig(value)); } catch { setMessage('表头配置保存失败'); } }} />}</div>;
}

export function StockDetailPage() { const { tsCode = '' } = useParams(); const navigate = useNavigate(); const [stock, setStock] = useState<StockDetail | null>(null); useEffect(() => { fetchStockDetail(tsCode).then(setStock); }, [tsCode]); if (!stock) return <div className="module-page page-wrap"><div className="loading-bar">正在加载个股详情…</div></div>; return <div className="module-page page-wrap"><button className="back-link" onClick={() => navigate('/stock-tracking')}>← 返回追踪列表</button><h1>{stock.stockName}</h1><p className="module-intro">{stock.tsCode} · 最新交易日 {stock.latestTradeDate ?? '暂无'}</p></div>; }
