import { useEffect, useState } from 'react';
import { fetchTaskLogs, fetchTasks, runTask, ScheduledTask, TaskLog, updateTask } from '../api/tasks';

export function TaskManagementPage() {
  const [tasks, setTasks] = useState<ScheduledTask[]>([]); const [logs, setLogs] = useState<Record<string, TaskLog[]>>({}); const [message, setMessage] = useState('');
  const load = () => fetchTasks().then(setTasks).catch(() => setMessage('任务列表加载失败，请检查管理令牌与 API 配置'));
  useEffect(() => { void load(); }, []);
  const change = async (task: ScheduledTask, values: Partial<Pick<ScheduledTask, 'enabled' | 'scheduleHour' | 'scheduleMinute'>>) => { try { await updateTask(task.taskKey, values); await load(); setMessage('任务配置已保存'); } catch { setMessage('任务配置保存失败'); } };
  const execute = async (task: ScheduledTask) => { try { await runTask(task.taskKey); setMessage(`${task.taskName} 执行完成`); await load(); } catch { setMessage(`${task.taskName} 执行失败，请查看日志`); } };
  const toggleLogs = async (key: string) => { if (logs[key]) { setLogs(({ [key]: _, ...rest }) => rest); return; } try { setLogs((old) => ({ ...old, [key]: [] })); const data = await fetchTaskLogs(key); setLogs((old) => ({ ...old, [key]: data })); } catch { setMessage('执行日志加载失败'); } };
  return <div className="module-page page-wrap"><p className="overline">TASK CENTER</p><h1>任务管理</h1><p className="module-intro">统一管理平台定时任务，查看运行状态与执行记录。</p>{message && <div className="notice">{message}</div>}<div className="task-list">{tasks.map((task) => <article className="task-card" key={task.taskKey}><div><strong>{task.taskName}</strong><span>{task.taskKey} · {task.timezone}</span><small>{task.lastSummary ?? '尚未执行'}{task.lastError ? ` · ${task.lastError}` : ''}</small><small>上次：{task.lastRunAt ? new Date(task.lastRunAt).toLocaleString() : '—'} · 下次：{task.nextRunAt ? new Date(task.nextRunAt).toLocaleString() : '调度器刷新后计算'}</small></div><label className="task-time">每天 <input type="number" min="0" max="23" value={task.scheduleHour} onChange={(e) => void change(task, { scheduleHour: Number(e.target.value) })} /> : <input type="number" min="0" max="59" value={task.scheduleMinute} onChange={(e) => void change(task, { scheduleMinute: Number(e.target.value) })} /></label><button className="text-button" onClick={() => void change(task, { enabled: !task.enabled })}>{task.enabled ? '运行中' : '已停止'}</button><button className="task-action" onClick={() => void execute(task)}>立即执行</button><button className="task-log-button" onClick={() => void toggleLogs(task.taskKey)}>执行记录</button>{logs[task.taskKey] && <div className="task-logs">{logs[task.taskKey].length === 0 ? '加载中…' : logs[task.taskKey].map((log) => <div key={log.id}><span>{new Date(log.startedAt).toLocaleString()}</span><b className={log.status}>{log.status === 'success' ? '成功' : '失败'}</b><span>{log.summary ?? log.errorDetail ?? '—'}</span></div>)}</div>}</article>)}</div></div>;
}
