import { PlayCircleOutlined, ReloadOutlined, UnorderedListOutlined } from '@ant-design/icons';
import { Alert, Button, Card, Flex, InputNumber, List, Space, Tag, Typography } from 'antd';
import { useEffect, useState } from 'react';
import { fetchTaskLogs, fetchTasks, runTask, ScheduledTask, TaskLog, updateTask } from '../api/tasks';

export function TaskManagementPage() {
  const [tasks, setTasks] = useState<ScheduledTask[]>([]); const [logs, setLogs] = useState<Record<string, TaskLog[]>>({}); const [message, setMessage] = useState('');
  const load = () => fetchTasks().then(setTasks).catch(() => setMessage('任务列表加载失败，请检查管理令牌与 API 配置'));
  useEffect(() => { void load(); }, []);
  const change = async (task: ScheduledTask, values: Partial<Pick<ScheduledTask, 'enabled' | 'scheduleHour' | 'scheduleMinute'>>) => { try { await updateTask(task.taskKey, values); await load(); setMessage('任务配置已保存'); } catch { setMessage('任务配置保存失败'); } };
  const execute = async (task: ScheduledTask) => { try { await runTask(task.taskKey); setMessage(task.taskName + ' 执行完成'); await load(); } catch { setMessage(task.taskName + ' 执行失败，请查看日志'); } };
  const toggleLogs = async (key: string) => { if (logs[key]) return setLogs(({ [key]: _, ...rest }) => rest); try { setLogs((old) => ({ ...old, [key]: [] })); const data = await fetchTaskLogs(key); setLogs((old) => ({ ...old, [key]: data })); } catch { setMessage('执行日志加载失败'); } };
  return <div className="module-page page-wrap"><Typography.Text className="overline">任务管理</Typography.Text><Typography.Title>任务管理</Typography.Title><Typography.Paragraph className="module-intro">统一管理平台定时任务，查看运行状态与执行记录。</Typography.Paragraph>{message && <Alert className="notice" type="info" showIcon title={message} closable onClose={() => setMessage('')} />}<Space direction="vertical" size={14} className="task-list" style={{ width: '100%' }}>{tasks.map((task) => <Card key={task.taskKey} className="task-card"><Flex justify="space-between" align="start" gap={20} wrap><div><Typography.Title level={4}>{task.taskName}</Typography.Title><Typography.Text type="secondary">每日执行 · {task.timezone}</Typography.Text><br /><Typography.Text type="secondary">{task.lastSummary ?? '尚未执行'}{task.lastError ? ' · ' + task.lastError : ''}</Typography.Text><br /><Typography.Text type="secondary">上次：{task.lastRunAt ? new Date(task.lastRunAt).toLocaleString() : '—'} · 下次：{task.nextRunAt ? new Date(task.nextRunAt).toLocaleString() : '调度器刷新后计算'}</Typography.Text></div><Space wrap><Space>每天 <InputNumber min={0} max={23} value={task.scheduleHour} onChange={(value) => value !== null && void change(task, { scheduleHour: value })} /> : <InputNumber min={0} max={59} value={task.scheduleMinute} onChange={(value) => value !== null && void change(task, { scheduleMinute: value })} /></Space><Button type={task.enabled ? 'primary' : 'default'} onClick={() => void change(task, { enabled: !task.enabled })}>{task.enabled ? '运行中' : '已停止'}</Button><Button icon={<PlayCircleOutlined />} onClick={() => void execute(task)}>立即执行</Button><Button icon={<UnorderedListOutlined />} onClick={() => void toggleLogs(task.taskKey)}>执行记录</Button></Space></Flex>{logs[task.taskKey] && <List size="small" header="执行记录" dataSource={logs[task.taskKey]} locale={{ emptyText: '暂无记录' }} renderItem={(log) => <List.Item><Space><Typography.Text type="secondary">{new Date(log.startedAt).toLocaleString()}</Typography.Text><Tag color={log.status === 'success' ? 'green' : 'red'}>{log.status === 'success' ? '成功' : '失败'}</Tag><Typography.Text>{log.summary ?? log.errorDetail ?? '—'}</Typography.Text></Space></List.Item>} />}</Card>)}</Space>{!tasks.length && <Button icon={<ReloadOutlined />} onClick={() => void load()}>重新加载</Button>}</div>;
}
