CREATE TABLE IF NOT EXISTS StockTableConfig (
    configKey VARCHAR(32) PRIMARY KEY,
    configJson JSON NOT NULL,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
