from datetime import datetime
from typing import Protocol

from app.domain.task.models import ScheduledTask, TaskExecutionLog


class TaskRepository(Protocol):
    def list_tasks(self) -> list[ScheduledTask]: ...
    def find_task(self, task_key: str) -> ScheduledTask | None: ...
    def save_task(self, task: ScheduledTask) -> ScheduledTask: ...
    def create_log(self, log: TaskExecutionLog) -> TaskExecutionLog: ...
    def finish_log(self, log_id: int, **values: object) -> TaskExecutionLog: ...
    def list_logs(self, task_key: str, limit: int) -> list[TaskExecutionLog]: ...
